name: rentoptions
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  toast: ^0.1.5
  url_launcher: ^5.5.0
  gsheets: ^0.2.5
  webview_flutter: ^0.3.22+1
  http: ^0.12.2
  carousel_slider: ^1.4.1
  google_fonts: ^1.1.0
  cached_network_image: ^2.3.1
  photo_view: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher/ic_launcher.png"

flutter:

  uses-material-design: true