name: rentoptions
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  toast: ^0.1.5
  url_launcher: ^5.5.0
  gsheets: ^0.2.5
  webview_flutter: ^0.3.22+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
